// Code generated by "stringer -type=Tool"; DO NOT EDIT.

package player

import "strconv"

const _Tool_name = "NoToolFishTrapFleshingBeamWeavingLoomSlaughteringTableSpadeShovelPairShovelPotteryWheelOvenAxeWorkbench"

var _Tool_index = [...]uint8{0, 6, 14, 26, 37, 54, 59, 69, 75, 87, 91, 94, 103}

func (i Tool) String() string {
	if i < 0 || i >= Tool(len(_Tool_index)-1) {
		return "Tool(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tool_name[_Tool_index[i]:_Tool_index[i+1]]
}
