// Code generated by "stringer -type=Good"; DO NOT EDIT.

package goods

import "strconv"

const _Good_name = "UndefinedWoodTimberClayBrickPeatFoodGrainHideFlaxWoolLinenWoolenLeatherSummerWearWinterWearLeatherWear"

var _Good_index = [...]uint8{0, 9, 13, 19, 23, 28, 32, 36, 41, 45, 49, 53, 58, 64, 71, 81, 91, 102}

func (i Good) String() string {
	if i < 0 || i >= Good(len(_Good_index)-1) {
		return "Good(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Good_name[_Good_index[i]:_Good_index[i+1]]
}
