// Code generated by "stringer -type=Month"; DO NOT EDIT.

package time

import "strconv"

const _Month_name = "JulyAugustSeptemberOctoberNovemberJanuaryFebruaryMarchAprilMay"

var _Month_index = [...]uint8{0, 4, 10, 19, 26, 34, 41, 49, 54, 59, 62}

func (i Month) String() string {
	if i < 0 || i >= Month(len(_Month_index)-1) {
		return "Month(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Month_name[_Month_index[i]:_Month_index[i+1]]
}
