// Code generated by "stringer -type=month"; DO NOT EDIT.

package time

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[july-0]
	_ = x[august-1]
	_ = x[september-2]
	_ = x[october-3]
	_ = x[november-4]
	_ = x[january-5]
	_ = x[february-6]
	_ = x[march-7]
	_ = x[april-8]
	_ = x[may-9]
}

const _month_name = "julyaugustseptemberoctobernovemberjanuaryfebruarymarchaprilmay"

var _month_index = [...]uint8{0, 4, 10, 19, 26, 34, 41, 49, 54, 59, 62}

func (i month) String() string {
	if i < 0 || i >= month(len(_month_index)-1) {
		return "month(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _month_name[_month_index[i]:_month_index[i+1]]
}
