// Code generated by "stringer -type=Action"; DO NOT EDIT.

package action

import "strconv"

const (
	_Action_name_0 = "FishermanGrocerWoolWeaverColonistPeatCutterDikeBuilderClayWorkerFarmerForesterWoodcutterMasterCarpenterBuilderWardenLaborer"
	_Action_name_1 = "PeatBoatmanTannerLinenWeaverButcherCattleTraderGrocer2BuildersMerchantPotterBakerWoodTraderMaster2WainwrightDikeWarderCarpenter2Laborer2"
	_Action_name_2 = "Finish"
	_Action_name_3 = "GetSheepGetCowGetHorseGetWoodGet4WoodGetTimberGetClayGetBrickGetFlaxFieldGetGrainFieldGetForest"
	_Action_name_4 = "UseSheepUseCowUseHorseUseWoodUseTimberUseClayUseBrickUseFlaxFieldUseGrainFieldUseForest"
	_Action_name_5 = "BuildVehicleBuildHorseCartBuildCarriageBuildDroshskyBuildHandcartBuildWagonBuildPeatBoatBuildPlow"
)

var (
	_Action_index_0 = [...]uint8{0, 9, 15, 25, 33, 43, 54, 64, 70, 78, 88, 94, 103, 110, 116, 123}
	_Action_index_1 = [...]uint8{0, 11, 17, 28, 35, 47, 54, 70, 76, 81, 91, 98, 108, 118, 128, 136}
	_Action_index_3 = [...]uint8{0, 8, 14, 22, 29, 37, 46, 53, 61, 73, 86, 95}
	_Action_index_4 = [...]uint8{0, 8, 14, 22, 29, 38, 45, 53, 65, 78, 87}
	_Action_index_5 = [...]uint8{0, 12, 26, 39, 52, 65, 75, 88, 97}
)

func (i Action) String() string {
	switch {
	case 2 <= i && i <= 16:
		i -= 2
		return _Action_name_0[_Action_index_0[i]:_Action_index_0[i+1]]
	case 18 <= i && i <= 32:
		i -= 18
		return _Action_name_1[_Action_index_1[i]:_Action_index_1[i+1]]
	case i == 34:
		return _Action_name_2
	case 36 <= i && i <= 46:
		i -= 36
		return _Action_name_3[_Action_index_3[i]:_Action_index_3[i+1]]
	case 48 <= i && i <= 57:
		i -= 48
		return _Action_name_4[_Action_index_4[i]:_Action_index_4[i+1]]
	case 59 <= i && i <= 66:
		i -= 59
		return _Action_name_5[_Action_index_5[i]:_Action_index_5[i+1]]
	default:
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
